Basic logic
bogomazdmitry/NotAlone pull request #2
Opened 2022-02-08 20:20 UTC by bogomazdmitry

2022-02-08 20:53 UTC, BlazeOfSoul commented on NotAlone.Services/ServiceExtension.cs
> +        public static void AddServices(this IServiceCollection services, IConfiguration configuration)
You can replace all this file to main and add your scoped services to HostBilder using .CobfigureServices

2022-02-08 20:53 UTC, BlazeOfSoul commented on NotAlone.WebApp/Startup.cs
> +using System;
And this file too. Create a file Program and unit 3 files in one using HostBuilder

2022-02-08 21:00 UTC, yarmoliq requested changes

2022-02-08 21:02 UTC, yarmoliq commented on NotAlone.WebApp/Controllers/HomeController.cs
> +                return Ok("Успешно!");
Exctract into a const

2022-02-08 21:02 UTC, yarmoliq commented on NotAlone.WebApp/Controllers/TestVkController.cs
> +                return Ok("Успешно!");
Extract into a const

2022-02-08 21:03 UTC, bogomazdmitry commented on NotAlone.WebApp/Models/ErrorViewModel.cs
> +        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
It is part of default application in asp.net :)

2022-02-08 21:04 UTC, yarmoliq requested changes

2022-02-08 21:04 UTC, yarmoliq commented on NotAlone.Services/VkService.cs
> +            var recipientId = recipient
You should probably do something like this
https://stackoverflow.com/a/659929/11651458

2022-02-08 21:04 UTC, bogomazdmitry commented on NotAlone.Services/VkService.cs
> +            if (request != null)
Vk send empty request everywere. I don't understand why, need to fix it

2022-02-08 21:05 UTC, bogomazdmitry commented on NotAlone.Services/ILoverHandlerService.cs
> +    public interface ILoverHandlerService
It is service for handling lovers info

2022-02-08 21:06 UTC, bogomazdmitry commented on NotAlone.Services/CreateMessageService.cs
> +            return "";
It is mock. It will be changed in the next PR

2022-02-09 08:34 UTC, bogomazdmitry commented on NotAlone.Models/LoverPeopleModel.cs
> +    public class LoverPeopleModel
Will be rename

2022-02-09 12:42 UTC, merged

2022-02-10 07:54 UTC, bogomazdmitry commented on NotAlone.Models/VkApiRequest.cs
> +        public JsonElement Object { get; set; }
Delete this class

2022-02-10 07:54 UTC, bogomazdmitry commented on NotAlone.Services/IVkService.cs
> +        string HandleRequest(JsonElement request);
Change to dynamic object

2022-02-10 07:54 UTC, bogomazdmitry commented on NotAlone.Services/VkService.cs
> +                            Message = _configuration["MessageTemplates:FirstMessageTemplate"],
Move constants to the environment and create classes for this

2022-02-10 07:54 UTC, bogomazdmitry commented on NotAlone.WebApp/ApiControllers/HomeApiController.cs
> +        public IActionResult Callback([FromBody] JsonElement request)
Move to the other controller

2022-02-10 07:54 UTC, bogomazdmitry commented on NotAlone.WebApp/Controllers/HomeController.cs
> +                return Ok("Успешно!");
It will be removed

2022-02-10 07:54 UTC, bogomazdmitry commented on NotAlone.WebApp/appsettings.Development.json
> +    "AccessToken": "620557986ba26a5bf111e6d3147bbecb011c2e5ed494625316480d6b17c9f2bcf06f43d1cd10ccde0db23",
![image](https://user-images.githubusercontent.com/55416122/153361651-27e3093e-7db6-4f4b-b51a-46ab6a390ca1.png)

2022-02-10 07:54 UTC, bogomazdmitry commented on NotAlone.WebApp/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.css
> +/*!
Add to the gitiignore lib files

2022-02-10 07:54 UTC, bogomazdmitry commented on docker-compose.yml
> +      - 5000:5000
Ports is an environment variable

2022-02-10 07:54 UTC, bogomazdmitry commented on Dockerfile
> +EXPOSE 5000
Delete this